export interface CatalogNode { id:string; title:string; slug:string; children?:CatalogNode[]; searchable?:boolean; }
export interface MonitorConfig {
  source:'kufar'; categoryId:string; subcategoryId?:string; region?:string; city?:string; query?:string;
  minPrice?:number; maxPrice?:number; condition?:'new'|'used'; seller?:'private'|'company'; minMarketDiscount?:number; mode?:'normal'|'sniper';
}
const node=(id:string,title:string,slug:string,children:CatalogNode[]=[],searchable=true):CatalogNode=>({id,title,slug,...(children.length?{children}:{}),...(searchable?{}:{searchable:false})});
const child=(id:string,title:string,slug:string):CatalogNode=>({id,title,slug});

export const KUFAR_CATALOG:CatalogNode[]=[
node('real_estate','Недвижимость','nedvizhimost',[child('1010','Квартиры','kvartiru'),child('1020','Дома, дачи, коттеджи','dom'),child('1040','Комнаты','komnatu'),child('1080','Земельные участки','uchastok'),child('1050','Коммерческая недвижимость','kommercheskaya'),child('1030','Гаражи и стоянки','garazh'),child('1120','Новостройки','novostrojki')]),
node('auto','Авто и запчасти','avto-i-zapchasti',[child('2010','Легковые автомобили','avtomobili'),child('2020','Прицепы','pricepy'),child('2030','Мототехника','mototekhnika'),child('2040','Запчасти, расходники','zapchasti'),child('2045','Аксессуары','aksessuary'),child('2050','Водный транспорт','vodnyj-transport'),child('2060','Грузовики и автобусы','gruzoviki-i-avtobusy'),child('2070','Инструмент и оборудование','instrument-oborudovanie'),child('2075','Шины и диски','shiny-diski'),child('2080','Сельхозтехника','selhoztekhnika'),child('2090','Спецтехника','spectekhnika'),child('2100','Услуги для авто','uslugi-dlya-avto'),child('2110','Автокресла и бустеры','avtokresla')]),
node('services','Услуги','uslugi',[child('13010','Услуги для авто','uslugi-dlya-avto'),child('13020','Бытовые услуги','bytovye-uslugi'),child('13030','Компьютерные услуги, интернет','kompyuternye-uslugi'),child('13040','Красота и здоровье','krasota-uslugi'),child('13050','Няни и сиделки','nyani'),child('13060','Переводчики и секретари','perevodchiki'),child('13070','Перевозки','perevozki'),child('13080','Реклама и полиграфия','reklama'),child('13090','Строительные работы','stroitelnye-raboty'),child('13100','Сад и благоустройство','sad-blagoustrojstvo'),child('13110','Услуги для животных','uslugi-zhivotnyh'),child('13120','Фото и видеосъемка','foto-video'),child('13130','Юридические услуги','yuridicheskie'),child('13140','Туристические услуги','turisticheskie'),child('13150','Прочие услуги','prochie-uslugi'),child('13160','Ремонт и пошив одежды','remont-odezhdy'),child('13170','Услуги для торжеств','uslugi-torzhestv'),child('13180','Ремонт мебели','remont-mebeli'),child('13190','Ремонт квартиры, дома','remont-kvartiry')]),
node('repair','Ремонт и стройка','remont-i-strojka',[child('14010','Строительный инструмент','stroitelnye-instrumenty'),child('14020','Сантехника','santehnika'),child('14030','Стройматериалы','stroymaterialy'),child('14040','Отделочные материалы','otdelochnye-materialy'),child('14050','Окна и двери','okna-dveri'),child('14060','Прочее для ремонта и стройки','prochee-remont'),child('14070','Строительство и ремонт','stroitelstvo-remont'),child('14080','Срубы, бытовки, кунги','sruby-bytovki-kungi'),child('14170','Ремонт квартиры, дома','remont-kvartiry')]),
node('hobby','Хобби, спорт и туризм','hobby-sport-i-turizm',[child('4010','CD, DVD, пластинки','cd-dvd'),child('4020','Спорттовары','sporttovary'),child('4030','Антиквариат и коллекции','antikvariat'),child('4040','Книги и журналы','knigi'),child('4050','Велосипеды','velosipedy'),child('4060','Охота и рыбалка','ohota-rybalka'),child('4070','Музыкальные инструменты','muzykalnye-instrumenty'),child('4080','Рукоделие','rukodelie'),child('4090','Туристические товары','turizm'),child('4100','Прочее','prochee-hobby'),child('4110','Туристические услуги','turisticheskie-uslugi')]),
node('kids','Всё для детей и мам','vsyo-dlya-detej-i-mam',[child('12010','Одежда до 1 года','odezhda-do-goda'),child('12020','Детская обувь','detskaya-obuv'),child('12030','Кроватки, манежи, стульчики','krovatki'),child('12040','Ходунки, шезлонги, качели','hodunki'),child('12050','Коляски','kolyaski'),child('12060','Автокресла и бустеры','detskie-avtokresla'),child('12070','Кормление и уход','kormlenie-i-uhod'),child('12080','Сумки-кенгуру и слинги','sumki-kenguru'),child('12090','Игрушки и книги','igrushki-i-knigi'),child('12100','Детский транспорт','detskij-transport'),child('12110','Товары для мам','tovary-dlya-mam'),child('12120','Одежда для беременных','odezhda-dlya-beremennyh'),child('12130','Прочие товары для детей','prochie-detskie-tovary'),child('12140','Одежда для девочек','odezhda-dlya-devochek'),child('12150','Одежда для мальчиков','odezhda-dlya-malchikov'),child('12160','Текстиль для детей','tekstil')]),
node('furniture','Мебель','mebel',[],false),
node('women_clothes','Женский гардероб','zhenskij-garderob',[child('8080','Женская одежда','zhenskaya-odezhda'),child('8100','Женская обувь','zhenskaya-obuv'),child('8020','Аксессуары и часы','aksessuary-i-chasy'),child('8060','Одежда для беременных','odezhda-dlya-beremennyh'),child('8050','Ремонт и пошив одежды','remont-poshiv')]),
node('animals','Животные','zhivotnye',[child('11010','Домашние питомцы','domashnie-pitomcy'),child('11020','Сельхоз животные','selhoz-zhivotnye'),child('11030','Товары для животных','tovary-dlya-zhivotnyh'),child('11040','Услуги для животных','uslugi-dlya-zhivotnyh'),child('11050','Вязка животных','vyazka')]),
node('home','Все для дома','vse-dlya-doma',[child('3060','Мебель и интерьер','mebel-interer'),child('3110','Хозяйственные товары','hozyajstvennye-tovary'),child('3100','Посуда и кухонные аксессуары','posuda'),child('3120','Комнатные растения','komnatnye-rasteniya'),child('3040','Бытовая техника','bytovaya-tehnika'),child('3130','Бытовые услуги','bytovye-uslugi'),child('3140','Ремонт мебели','remont-mebeli')]),
node('phones','Телефоны и планшеты','telefony-i-planshety',[child('17010','Мобильные телефоны','mobilnye-telefony'),child('17020','Комплектующие для телефонов','komplektuyushchie-dlya-telefonov'),child('17030','Аксессуары для телефонов','aksessuary-dlya-telefonov'),child('17040','Телефония и связь','telefoniya-i-svyaz'),child('17050','Планшеты','planshety'),child('17120','Комплектующие для планшетов','komplektuyushchie-dlya-planshetov'),child('17060','Графические планшеты','graficheskie-planshety'),child('17070','Электронные книги','elektronnye-knigi'),child('17090','Умные часы и фитнес-браслеты','umnye-chasy-i-fitnes-braslety'),child('5100','Наушники','naushniki')]),
node('garden','Сад и огород','sad-i-ogorod',[child('10010','Садовая мебель и мангалы','sadovaya-mebel'),child('10020','Растения, рассада и семена','rasteniya'),child('10030','Садовая техника и инвентарь','sadovaya-tehnika'),child('10040','Теплицы','teplicy'),child('10050','Садовые аксессуары','sadovye-aksessuary'),child('10060','Удобрения и агрохимия','udobreniya'),child('10070','Все для пчеловода','pchelovodstvo'),child('10080','Прочее для сада и огорода','prochee-sad'),child('10090','Бани, хозблоки, санузлы','bani-hozbloki')]),
node('electronics','Электроника','elektronika',[child('5020','Аудиотехника','audiotekhnika'),child('5060','ТВ и видеотехника','televizory'),child('5070','Фототехника и оптика','fototekhnika'),child('5040','Игры и приставки','igry-i-pristavki')]),
node('computers','Компьютерная техника','kompyuternaya-tehnika',[child('5030','Компьютеры и комплектующие','kompyutery-i-komplektuyushchie')]),
node('home_appliances','Бытовая техника','bytovaya-tehnika',[child('5090','Бытовая техника','bytovaya-tehnika')]),
node('men_clothes','Мужской гардероб','muzhskoj-garderob',[child('8070','Мужская одежда','muzhskaya-odezhda'),child('8090','Мужская обувь','muzhskaya-obuv')]),
node('business','Готовый бизнес и оборудование','gotovyj-biznes-i-oborudovanie',[child('6050','Готовый бизнес','gotovyj-biznes'),child('6090','Станки и оборудование','stanki-oborudovanie')]),
node('beauty','Красота и здоровье','krasota-i-zdorove',[child('8110','Косметика и парфюмерия','kosmetika-parfyumeriya')]),
node('jobs','Работа','rabota',[child('6010','Вакансии','vakansii'),child('6020','Ищу работу','ischu-rabotu'),child('6040','Образование','obrazovanie')]),
node('other','Прочее','prochee',[child('7010','Все остальное','vse-ostalnoe'),child('7020','Продукты питания','produkty'),child('7030','Бюро находок','byuro-nahodok'),child('7040','Спрос','spros'),child('7050','Медицинские товары','medicinskie-tovary'),child('7060','Канцелярские товары','kancelyariya')]),
node('wedding','Свадьба и праздники','svadba-i-prazdniki',[child('9010','Подарки и праздничные товары','podarki'),child('9020','Свадебные платья','svadebnye-platya'),child('9030','Свадебные костюмы','svadebnye-kostyumy'),child('9040','Свадебная обувь','svadebnaya-obuv'),child('9050','Свадебные аксессуары','svadebnye-aksessuary'),child('9060','Услуги для торжеств','uslugi-torzhestv'),child('9070','Карнавальные костюмы','karnavalnye-kostyumy')]),
node('travel','Путешествия — жильё на сутки','puteshestviya-zhilyo-na-sutki',[],false)
];

const REGION_SLUGS:Record<string,string>={minsk:'minsk',brest:'brest',vitebsk:'vitebsk',gomel:'gomel',grodno:'grodno',mogilev:'mogilev',minskaya_oblast:'minskaya-oblast',brestskaya_oblast:'brestskaya-oblast',vitebskaya_oblast:'vitebskaya-oblast',gomelskaya_oblast:'gomelskaya-oblast',grodnenskaya_oblast:'grodnenskaya-oblast',mogilevskaya_oblast:'mogilevskaya-oblast'};

export function findCatalogNode(id:string):CatalogNode|null{for(const category of KUFAR_CATALOG){if(category.id===id)return category;const found=category.children?.find(item=>item.id===id);if(found)return found;}return null;}
export function findCatalogCategory(id:string):CatalogNode|null{const direct=KUFAR_CATALOG.find(category=>category.id===id);if(direct)return direct;return KUFAR_CATALOG.find(category=>category.children?.some(item=>item.id===id))||null;}
export function getCatalogLabel(id:string):string{return findCatalogNode(id)?.title||'Каталог';}
export function buildKufarSearchUrl(config:MonitorConfig):string{
 const selected=findCatalogNode(config.subcategoryId||config.categoryId); const category=findCatalogCategory(config.categoryId); const slug=selected?.slug||category?.slug||'';
 const city=config.city?encodeURIComponent(config.city):''; const region=config.region?REGION_SLUGS[config.region]||config.region:'';
 const prefix=city?'/l/r~'+city+'/':region?'/l/r~'+region+'/':'/l/'; const url=new URL(prefix+slug,'https://www.kufar.by');
 if(config.query?.trim())url.searchParams.set('query',config.query.trim());
 const min=config.minPrice!=null&&Number.isFinite(Number(config.minPrice))?Number(config.minPrice):undefined;
 const max=config.maxPrice!=null&&Number.isFinite(Number(config.maxPrice))?Number(config.maxPrice):undefined;
 if(min!=null||max!=null)url.searchParams.set('prc','r:'+(min??0)+','+(max??''));
 const identity=[config.source,config.categoryId,config.subcategoryId||'',config.region||'',config.city||'',config.query?.trim()||'',min??'',max??'',config.condition||'',config.seller||'',config.mode||'normal'].join('|');
 url.searchParams.set('wb',identity); return url.toString();
}
