export interface CatalogNode { id:string; title:string; slug:string; children?:CatalogNode[]; searchable?:boolean; }
export interface MonitorConfig {
  source:'kufar'|'onliner'|'av'; categoryId:string; subcategoryId?:string; brand?:string; model?:string; phoneFilters?:Record<string,string|string[]|boolean>; region?:string; city?:string; query?:string;
  minPrice?:number; maxPrice?:number; condition?:'new'|'used'; seller?:'private'|'company'; minMarketDiscount?:number; skipSlots?:number; mode?:'normal'|'sniper';
}
const node=(id:string,title:string,slug:string,children:CatalogNode[]|CatalogNode[]=[],searchable:boolean|CatalogNode=true,...extraChildren:CatalogNode[]):CatalogNode=>{const list=Array.isArray(children)?children:[children as CatalogNode,...(typeof searchable==='object'?[searchable]:[]),...extraChildren];const isSearchable=typeof searchable==='boolean'?searchable:true;return {id,title,slug,...(list.length?{children:list}:{}),...(isSearchable?{}:{searchable:false})};}
const child=(id:string,title:string,slug:string,...children:CatalogNode[]):CatalogNode=>({id,title,slug,...(children.length?{children}:{}),});

export const KUFAR_CATALOG:CatalogNode[]=[
node('real_estate','Недвижимость','nedvizhimost',[child('1010','Квартиры — продажа','kvartiru'),child('1011','Квартиры — аренда на длительный срок','arenda-kvartir'),child('1012','Квартиры — посуточно','kvartiry-na-sutki'),child('1013','Квартиры — 1-комнатные','kvartiru-1k'),child('1014','Квартиры — 2-комнатные','kvartiru-2k'),child('1015','Квартиры — 3-комнатные','kvartiru-3k'),child('1016','Квартиры — 4+ комнатные','kvartiru-4k'),child('1020','Дома, дачи, коттеджи — продажа','dom'),child('1021','Дома, коттеджи — аренда','arenda-domov'),child('1022','Дома, коттеджи — посуточно','dom-na-sutki'),child('1040','Комнаты — продажа','komnatu'),child('1041','Комнаты — аренда','arenda-komnat'),child('1080','Земельные участки','uchastok'),child('1050','Коммерческая недвижимость','kommercheskaya'),child('1051','Коммерческая недвижимость — аренда','arenda-kommercheskoj'),child('1030','Гаражи и стоянки — продажа','garazh'),child('1031','Гаражи и стоянки — аренда','arenda-garazhej'),child('1120','Новостройки','novostrojki',child('1121','Квартиры в новостройках','kvartiry-novostrojki'),child('1122','Дома и коттеджи в новостройках','doma-novostrojki'),child('1123','Долевое строительство','dolevoe-stroitelstvo'))]),
node('auto','Авто и запчасти','avto-i-zapchasti',[child('2010','Легковые автомобили','avtomobili'),child('2020','Прицепы','pricepy'),child('2030','Мототехника','mototekhnika'),child('2040','Запчасти, расходники','zapchasti'),child('2045','Аксессуары','aksessuary'),child('2050','Водный транспорт','vodnyj-transport'),child('2060','Грузовики и автобусы','gruzoviki-i-avtobusy'),child('2070','Инструмент и оборудование','instrument-oborudovanie'),child('2075','Шины и диски','shiny-diski'),child('2080','Сельхозтехника','selhoztekhnika'),child('2090','Спецтехника','spectekhnika'),child('2100','Услуги для авто','uslugi-dlya-avto'),child('2110','Автокресла и бустеры','avtokresla',child('2011','Электромобили','elektromobili'),child('2012','Гибриды','gibridy'),child('2013','Легковые автомобили новые','novye-avtomobili'),child('2021','Полуприцепы','polupricepy'),child('2031','Скутеры и мопеды','skutery-mopedy'),child('2032','Квадроциклы и снегоходы','kvadrocikly-snegohody'),child('2041','Двигатели и агрегаты','dvigateli'),child('2042','Кузовные детали','kuzovnye-detali'),child('2043','Оптика и освещение','optika'),child('2044','Тормозная система','tormoznaya-sistema'),child('2071','Домкраты и подъемники','domkraty-podemniki'),child('2076','Шины легковые','shiny-legkovye'),child('2077','Шины грузовые','shiny-gruzovye'),child('2078','Диски','diski'),child('2081','Минитракторы','minitraktory'),child('2091','Дорожно-строительная техника','dorozhno-stroitelnaya'),child('2092','Погрузчики','pogruzchiki'))]),
node('services','Услуги','uslugi',[child('13010','Услуги для авто','uslugi-dlya-avto'),child('13020','Бытовые услуги','bytovye-uslugi'),child('13030','Компьютерные услуги, интернет','kompyuternye-uslugi'),child('13031','Ремонт техники и электроники','remont-tehniki'),child('13040','Красота','krasota'),child('13041','Здоровье','zdorove'),child('13050','Няни и сиделки','nyani'),child('13060','Образовательные услуги','obrazovatelnye-uslugi'),child('13070','Грузоперевозки','gruzoperevozki'),child('13071','Пассажирские перевозки','passazhirskie-perevozki'),child('13072','Услуги грузчиков','gruzchiki'),child('13073','Услуги эвакуатора','evakuator'),child('13074','Вывоз мусора','vyvoz-musora'),child('13080','Полиграфия, наружная реклама','poligrafiya-reklama'),child('13090','Строительные работы','stroitelnye-raboty'),child('13190','Ремонт квартиры, дома','remont-kvartiry'),child('13180','Ремонт, сборка, перетяжка мебели','remont-mebeli'),child('13160','Ремонт и пошив одежды','remont-odezhdy'),child('13100','Сад, благоустройство','sad-blagoustrojstvo'),child('13110','Услуги для животных','uslugi-zhivotnyh'),child('13170','Услуги для торжеств','uslugi-torzhestv'),child('13120','Фото и видеосъемка','foto-video'),child('13130','Деловые услуги','delovye-uslugi'),child('13140','Впечатления','vpechatleniya'),child('13141','Аренда и прокат','arenda-prokat'),child('13142','Аренда бань и беседок','arenda-ban-besedok'),child('13150','Прочие услуги','prochie-uslugi'),child('13151','Ритуальные товары и услуги','ritualnye-uslugi'))]),
node('repair','Ремонт и стройка','remont-i-strojka',[child('14010','Строительный инструмент','stroitelnye-instrumenty'),child('14020','Сантехника','santehnika'),child('14030','Стройматериалы','stroymaterialy'),child('14040','Отделочные материалы','otdelochnye-materialy'),child('14050','Окна и двери','okna-dveri'),child('14060','Прочее для ремонта и стройки','prochee-remont'),child('14070','Строительство и ремонт','stroitelstvo-remont'),child('14080','Срубы, бытовки, кунги','sruby-bytovki-kungi'),child('14170','Ремонт квартиры, дома','remont-kvartiry',child('14011','Электроинструмент','elektroinstrument'),child('14012','Сварочное оборудование','svarochnoe-oborudovanie'),child('14031','Кирпич, блоки, бетон','kirpich-bloki'),child('14032','Пиломатериалы','pilomaterialy'),child('14033','Кровельные материалы','krovelnye-materialy'),child('14041','Обои','oboi'),child('14042','Плитка','plitka'),child('14043','Ламинат, паркет','laminat-parket'),child('14051','Межкомнатные двери','mezhkomnatnye-dveri'),child('14052','Входные двери','vhodnye-dveri'),child('14061','Лакокрасочные материалы','lakokrasochnye'),child('14062','Электрика и освещение','elektrika-osveshchenie'),child('14071','Кровельные работы','krovelnye-raboty'),child('14072','Сантехнические работы','santehnicheskie-raboty'))]),
node('hobby','Хобби, спорт и туризм','hobby-sport-i-turizm',[child('4010','CD, DVD, пластинки','cd-dvd'),child('4020','Спорттовары','sporttovary'),child('4030','Антиквариат и коллекции','antikvariat'),child('4040','Книги и журналы','knigi'),child('4050','Велосипеды','velosipedy'),child('4060','Охота и рыбалка','ohota-rybalka'),child('4070','Музыкальные инструменты','muzykalnye-instrumenty'),child('4080','Рукоделие','rukodelie'),child('4090','Туристические товары','turizm'),child('4100','Прочее','prochee-hobby'),child('4110','Туристические услуги','turisticheskie-uslugi',child('4021','Тренажеры и фитнес','trenazhery'),child('4022','Футбол и хоккей','futbol-hokkej'),child('4023','Зимний спорт','zimnij-sport'),child('4024','Водный спорт','vodnyj-sport'),child('4025','Единоборства','edinoborstva'),child('4051','Велозапчасти','velozapchasti'),child('4052','Электровелосипеды','elektrovelosipedy'),child('4091','Палатки и спальники','palatki-spalniki'),child('4092','Рюкзаки и туристическая посуда','turisticheskoe-snaryazhenie'),child('4101','Настольные игры','nastolnye-igry'),child('4102','Коллекционирование','kollekcionirovanie'),child('4103','Книги и журналы','knigi-zhurnaly'))]),
node('kids','Всё для детей и мам','vsyo-dlya-detej-i-mam',[child('12010','Одежда до 1 года','odezhda-do-goda'),child('12140','Одежда для девочек','odezhda-dlya-devochek'),child('12150','Одежда для мальчиков','odezhda-dlya-malchikov'),child('12020','Детская обувь','detskaya-obuv'),child('12050','Коляски','kolyaski'),child('12030','Кроватки, манежи, стульчики','krovatki'),child('12040','Ходунки, шезлонги, качели','hodunki'),child('12060','Автокресла и бустеры','detskie-avtokresla'),child('12070','Кормление и уход','kormlenie-i-uhod'),child('12080','Сумки-кенгуру и слинги','sumki-kenguru'),child('12090','Игрушки и книги','igrushki-i-knigi'),child('12100','Детский транспорт','detskij-transport'),child('12160','Текстиль для детей','tekstil'),child('12110','Товары для мам','tovary-dlya-mam'),child('12120','Одежда для беременных','odezhda-dlya-beremennyh'),child('12130','Прочие товары для детей','prochie-detskie-tovary',child('12131','Детская мебель','detskaya-mebel'),child('12132','Детский текстиль','detskij-tekstil'),child('12133','Детское питание','detskoe-pitanie'),child('12134','Товары для школы','tovary-dlya-shkoly'),child('12135','Детские праздники','detskie-prazdniki'))]),
node('furniture','Мебель','mebel',[child('3061','Диваны и кресла','divany-kresla'),child('3062','Кровати и матрасы','krovati-matrasy'),child('3063','Шкафы и комоды','shkafy-komody'),child('3064','Столы и стулья','stoly-stulya'),child('3065','Кухонная мебель','kuhonnaya-mebel'),child('3066','Мебель для ванной','mebel-vannaya'),child('3067','Офисная мебель','ofisnaya-mebel'),child('3068','Мебельная фурнитура и составляющие','mebelnaya-furnitura'),child('3069','Прочая мебель','prochaya-mebel',child('3070','Детская мебель','detskaya-mebel'),child('3071','Мебель для прихожей','mebel-prihozhaya'),child('3072','Мебель для гостиной','mebel-gostinaya'),child('3073','Мебель для спальни','mebel-spalnya'),child('3074','Мебель для офиса','mebel-ofisa'),child('3075','Мебель на заказ','mebel-na-zakaz'))]),
node('women_clothes','Женский гардероб','zhenskij-garderob',[child('8075','Премиум одежда','premium-odezhda'),child('8080','Женская одежда','zhenskaya-odezhda'),child('8081','Женская верхняя одежда','zhenskaya-verhnyaya-odezhda'),child('8082','Джинсы и брюки','zhenskie-dzhinsy-bryuki'),child('8083','Платья и сарафаны','platya-sarafany'),child('8084','Сумки','sumki'),child('8100','Женская обувь','zhenskaya-obuv'),child('8101','Кроссовки и кеды','krossovki-kedy'),child('8020','Женские аксессуары и часы','zhenskie-aksessuary'),child('8021','Украшения','ukrasheniya'),child('8060','Одежда для беременных','odezhda-dlya-beremennyh'),child('8050','Ремонт и пошив одежды','remont-poshiv'))]),
node('animals','Животные','zhivotnye',[child('11000','Питомцы в дар','pitomcy-v-dar'),child('11010','Домашние питомцы','domashnie-pitomcy'),child('11020','Сельхоз животные','selhoz-zhivotnye'),child('11030','Товары для животных','tovary-dlya-zhivotnyh'),child('11040','Услуги для животных','uslugi-dlya-zhivotnyh'),child('11050','Вязка животных','vyazka'))]),
node('home','Все для дома','vse-dlya-doma',[child('3060','Мебель и интерьер','mebel-interer'),child('3110','Хозяйственные товары','hozyajstvennye-tovary'),child('3100','Посуда и кухонные аксессуары','posuda'),child('3120','Комнатные растения','komnatnye-rasteniya'),child('3040','Бытовая техника','bytovaya-tehnika'),child('3130','Бытовые услуги','bytovye-uslugi'),child('3140','Ремонт мебели','remont-mebeli',child('3121','Освещение','osveshchenie'),child('3122','Ковры и текстиль','kovry-tekstil'),child('3123','Декор и интерьер','dekor-interer'),child('3124','Хранение и организация','hranenie'),child('3125','Кухонные принадлежности','kuhonnye-prinadlezhnosti'),child('3126','Товары для уборки','tovary-dlya-uborki'))]),
node('phones','Телефоны и планшеты','telefony-i-planshety',[child('17010','Мобильные телефоны','mobilnye-telefony'),child('17020','Комплектующие для телефонов','komplektuyushchie-dlya-telefonov'),child('17030','Аксессуары для телефонов','aksessuary-dlya-telefonov'),child('17040','Телефония и связь','telefoniya-i-svyaz'),child('17050','Планшеты','planshety'),child('17120','Аксессуары для планшетов и книг','aksessuary-planshety-knigi'),child('17060','Графические планшеты','graficheskie-planshety'),child('17070','Электронные книги','elektronnye-knigi'),child('17090','Умные часы и фитнес-браслеты','umnye-chasy-i-fitnes-braslety'),child('17091','Аксессуары для умных часов','aksessuary-smartwatch'),child('5100','Наушники','naushniki'))]),
node('garden','Сад и огород','sad-i-ogorod',[child('10010','Садовая мебель и мангалы','sadovaya-mebel'),child('10011','Мангалы, аксессуары, топливо','mangaly'),child('10020','Садовые растения, рассада и семена','rasteniya'),child('10021','Семена, луковицы','semena-lukovicy'),child('10030','Садовая техника и инвентарь','sadovaya-tehnika'),child('10031','Садовый инструмент','sadovyj-instrument'),child('10040','Теплицы','teplicy'),child('10050','Садовые аксессуары','sadovye-aksessuary'),child('10060','Удобрения и агрохимия','udobreniya'),child('10070','Все для пчеловода','pchelovodstvo'),child('10090','Бани, хозблоки, санузлы','bani-hozbloki'),child('10080','Прочее для сада и огорода','prochee-sad'))]),
node('electronics','Электроника','elektronika',[child('5020','Аудиотехника','audiotekhnika'),child('5021','Наушники','naushniki'),child('5022','Колонки и акустика','kolonki'),child('5023','Микрофоны','mikrofony'),child('5060','ТВ и видеотехника','televizory'),child('5061','Проекторы','proektory'),child('5062','Плееры и медиаприставки','mediapleery'),child('5070','Фототехника и оптика','fototekhnika'),child('5071','Фотоаппараты','fotoapparaty'),child('5072','Объективы','obektivy'),child('5073','Видеокамеры','videokamery'),child('5040','Игры и приставки','igry-i-pristavki'),child('5041','Игровые консоли','igrovye-pristavki'),child('5042','Игры','igry'),child('5080','Кабели, зарядки и аксессуары','elektronika-aksessuary'))]),
node('computers','Компьютерная техника','kompyuternaya-tehnika',[child('5034','Ноутбуки','noutbuki'),child('5039','Игровые ноутбуки','igrovye-noutbuki'),child('5045','Apple MacBook','apple-macbook'),child('5032','Компьютеры / системные блоки','kompyutery-sistemnye-bloki'),child('5031','Комплектующие','komplektuyushchie'),child('5033','Мониторы','monitory'),child('5046','Игровые мониторы','igrovye-monitory'),child('5035','Оргтехника','orgtehnika'),child('5036','Периферия и аксессуары','periferiya'),child('5038','Сетевое оборудование','setevoe-oborudovanie'),child('5047','Игровые устройства и аксессуары','igrovye-aksessuary'),child('5037','Прочие компьютерные товары','prochie-kompyuternye'))]),
node('home_appliances','Бытовая техника','bytovaya-tehnika',[child('5093','Техника для кухни','tehnika-dlya-kuhni'),child('5095','Холодильники и морозильники','holodilniki'),child('5096','Плиты и духовки','plity-duhovki'),child('5097','Варочные панели и вытяжки','varochnye-paneli'),child('5098','Посудомоечные машины','posudomojki'),child('5099','Стиральные и сушильные машины','stiralnye'),child('5101','Пылесосы','pylesosy'),child('5091','Климатическая техника','klimaticheskaya-tehnika'),child('5092','Техника для красоты и здоровья','tehnika-krasota'),child('5094','Уход за одеждой, пошив','uhod-odezhda'),child('5102','Мелкая бытовая техника','melkaya-bytovaya-tehnika'))]),
node('men_clothes','Мужской гардероб','muzhskoj-garderob',[child('8070','Мужская одежда','muzhskaya-odezhda'),child('8090','Мужская обувь','muzhskaya-obuv',child('8071','Мужская верхняя одежда','muzhskaya-verhnyaya-odezhda'),child('8072','Мужские брюки и джинсы','muzhskie-bryuki-dzhinsy'),child('8073','Мужские рубашки и футболки','muzhskie-rubashki-futbolki'),child('8074','Мужские костюмы','muzhskie-kostyumy'),child('8091','Мужская зимняя обувь','muzhskaya-zimnyaya-obuv'),child('8092','Мужская летняя обувь','muzhskaya-letnyaya-obuv'),child('8093','Мужские кроссовки','muzhskie-krossovki'))]),
node('business','Готовый бизнес и оборудование','gotovyj-biznes-i-oborudovanie',[child('6050','Готовый бизнес','gotovyj-biznes'),child('6090','Станки и оборудование','stanki-oborudovanie'))]),
node('beauty','Красота и здоровье','krasota-i-zdorove',[child('8110','Косметика и парфюмерия','kosmetika-parfyumeriya'),child('8111','Декоративная косметика','dekorativnaya-kosmetika'),child('8112','Уходовая косметика','uhodovaya-kosmetika'),child('8113','Средства для волос','sredstva-dlya-volos'),child('8114','Маникюр, педикюр','manikyur-pedikyur'),child('8115','Ресницы и брови, татуаж','resnicy-brovi'),child('8116','Средства гигиены, депиляция','gigiena-depilyaciya'),child('8117','Медицинские товары','medicinskie-tovary',child('8118','Товары для здоровья','tovary-zdorovya'),child('8119','Товары для фитнеса и похудения','fitnes-zdorovye'),child('8120','Солнцезащитные средства','solncezashchitnye'),child('8121','Уход за кожей лица','uhod-kozha-lica'),child('8122','Уход за телом','uhod-za-telom'),child('8123','Уход за волосами','uhod-za-volosami'))]),
node('jobs','Работа','rabota',[child('6010','Вакансии','vakansii'),child('6020','Ищу работу','ischu-rabotu'),child('6040','Образование','obrazovanie',child('6030','Работа за рубежом','rabota-za-rubezhom'),child('6031','Подработка','podrabotka'),child('6032','Удаленная работа','udalennaya-rabota'),child('6033','Работа для студентов','rabota-studentam'),child('6034','Водители и курьеры','voditeli-kurery'))]),
node('other','Прочее','prochee',[child('7010','Все остальное','vse-ostalnoe'),child('7020','Продукты питания','produkty'),child('7030','Бюро находок','byuro-nahodok'),child('7040','Спрос','spros'),child('7050','Медицинские товары','medicinskie-tovary'),child('7060','Канцелярские товары','kancelyariya',child('7070','Отдам даром','otdam-darom'),child('7071','Приму в дар','primu-v-dar'),child('7072','Продукты и напитки','produkty-napitki'),child('7073','Бытовая химия','bytovaya-himiya'),child('7074','Канцелярия и товары для школы','kancelyariya-shkola'))]),
node('wedding','Свадьба и праздники','svadba-i-prazdniki',[child('9010','Подарки и праздничные товары','podarki'),child('9020','Свадебные платья','svadebnye-platya'),child('9030','Свадебные костюмы','svadebnye-kostyumy'),child('9040','Свадебная обувь','svadebnaya-obuv'),child('9050','Свадебные аксессуары','svadebnye-aksessuary'),child('9060','Услуги для торжеств','uslugi-torzhestv'),child('9070','Карнавальные костюмы','karnavalnye-kostyumy'),child('9080','Декор и оформление','dekor-prazdnika'),child('9090','Прокат праздничных товаров','prokat-prazdnika'))]),
node('travel','Путешествия — жильё на сутки','puteshestviya-zhilyo-na-sutki',[child('18010','Квартиры посуточно','kvartiry'),child('18020','Дома и коттеджи посуточно','doma'),child('18030','Комнаты посуточно','komnaty'),child('18040','Бани и беседки','bani-besedki'),child('18050','Гостиницы и апартаменты','gostinicy')])
];

const REGION_SLUGS:Record<string,string>={minsk:'minsk',brest:'brest',vitebsk:'vitebsk',gomel:'gomel',grodno:'grodno',mogilev:'mogilev',minskaya_oblast:'minskaya-oblast',brestskaya_oblast:'brestskaya-oblast',vitebskaya_oblast:'vitebskaya-oblast',gomelskaya_oblast:'gomelskaya-oblast',grodnenskaya_oblast:'grodnenskaya-oblast',mogilevskaya_oblast:'mogilevskaya-oblast'};

export function findCatalogNode(id:string):CatalogNode|null{
 const walk=(nodes:CatalogNode[]):CatalogNode|null=>{for(const item of nodes){if(item.id===id)return item;const found=item.children?walk(item.children):null;if(found)return found;}return null};
 return walk(KUFAR_CATALOG);
}
export function findCatalogCategory(id:string):CatalogNode|null{
 const walk=(nodes:CatalogNode[],root:CatalogNode):CatalogNode|null=>{for(const item of nodes){if(item.id===id)return root;const found=item.children?walk(item.children,root):null;if(found)return found;}return null};
 const direct=KUFAR_CATALOG.find(category=>category.id===id); if(direct)return direct;
 for(const root of KUFAR_CATALOG){const found=walk(root.children||[],root);if(found)return found;} return null;
}export function buildKufarSearchUrl(config:MonitorConfig):string{
 const selected=findCatalogNode(config.subcategoryId||config.categoryId); const category=findCatalogCategory(config.categoryId); const baseSlug=selected?.slug||category?.slug||''; const rentalPaths:Record<string,string>={'1011':'/l/belarus/snyat/kvartiru','1012':'/l/belarus/snyat/kvartiru-na-sutki','1021':'/l/belarus/snyat/dom','1022':'/l/belarus/snyat/dom-na-sutki','1041':'/l/belarus/snyat/komnatu','1051':'/l/belarus/snyat/kommercheskuyu-nedvizhimost','1031':'/l/belarus/snyat/garazh'}; const phone=category?.id==='phones' || selected?.id==='17010'; const brand=phone&&config.brand?.trim()?config.brand.trim().toLocaleLowerCase('en-US').replace(/[^a-z0-9]+/g,'-'):''; const model=phone&&config.model?.trim()?config.model.trim().toLocaleLowerCase('ru-RU').replace(/[^a-z0-9а-яё]+/gi,'-').replace(/^-+|-+$/g,''):''; const slug=phone&&brand ? ('mobilnye-telefony/mt~'+brand+(model?'-'+model:'')) : baseSlug;
 const city=config.city?encodeURIComponent(config.city):''; const region=config.region?REGION_SLUGS[config.region]||config.region:'';
 const rentalPath=config.subcategoryId&&rentalPaths[config.subcategoryId]?rentalPaths[config.subcategoryId]:''; const prefix=city?'/l/r~'+city+'/':region?'/l/r~'+region+'/':'/l/'; const url=rentalPath?new URL(rentalPath,'https://re.kufar.by'):new URL(prefix+slug,'https://www.kufar.by');
 if(config.query?.trim())url.searchParams.set('query',config.query.trim());
 const min=config.minPrice!=null&&Number.isFinite(Number(config.minPrice))?Number(config.minPrice):undefined;
 const max=config.maxPrice!=null&&Number.isFinite(Number(config.maxPrice))?Number(config.maxPrice):undefined;
 if(min!=null||max!=null)url.searchParams.set('prc','r:'+(min??0)+','+(max??''));
 const identity=[config.source,config.categoryId,config.subcategoryId||'',config.brand||'',config.model||'',JSON.stringify(config.phoneFilters||{}),config.region||'',config.city||'',config.query?.trim()||'',min??'',max??'',config.condition||'',config.seller||'',config.mode||'normal',config.minMarketDiscount??'',config.skipSlots??0].join('|');
 url.searchParams.set('wb',identity); return url.toString();
}
