export interface CatalogNode { id:string; title:string; slug:string; children?:CatalogNode[]; }
export interface MonitorConfig {
  source:'kufar'; categoryId:string; subcategoryId?:string; region?:string; city?:string; query?:string;
  minPrice?:number; maxPrice?:number; condition?:'new'|'used'; seller?:'private'|'company'; mode?:'normal'|'sniper';
}
const node=(id:string,title:string,slug:string,children:CatalogNode[]=[]):CatalogNode=>({id,title,slug,...(children.length?{children}:{})});
const child=(id:string,title:string,slug:string):CatalogNode=>({id,title,slug});

/* WellBOT-owned UX taxonomy. Labels follow Kufar's current top-level categories. */
export const KUFAR_CATALOG:CatalogNode[]=[
 node('real_estate','Недвижимость','nedvizhimost',[child('1010','Квартиры','kvartiru'),child('1020','Дома и коттеджи','dom'),child('1040','Комнаты','komnatu'),child('1080','Земельные участки','uchastok'),child('1050','Коммерческая недвижимость','kommercheskaya'),child('1030','Гаражи','garazh')]),
 node('travel','Путешествия','puteshestviya'),
 node('auto','Авто и запчасти','avto-i-zapchasti',[child('2010','Легковые автомобили','avtomobili'),child('2020','Прицепы','pricepy'),child('2030','Мототехника','mototekhnika'),child('2040','Запчасти, расходники','zapchasti'),child('2045','Аксессуары','aksessuary'),child('2050','Водный транспорт','vodnyj-transport'),child('2060','Грузовики и автобусы','gruzoviki-i-avtobusy'),child('2070','Инструмент и оборудование','instrument-oborudovanie'),child('2075','Шины и диски','shiny-diski'),child('2080','Сельхозтехника','selhoztekhnika'),child('2090','Спецтехника','spectekhnika'),child('2100','Услуги для авто','uslugi-dlya-avto'),child('2110','Автокресла и бустеры','avtokresla')]),
 node('services','Услуги','uslugi'),
 node('home_appliances','Бытовая техника','bytovaya-tehnika',[child('3040','Бытовая техника','bytovaya-tehnika'),child('14050','Стиральные машины','stiralnye-mashiny')]),
 node('computers','Компьютерная техника','kompyuternaya-tehnika',[child('19020','Ноутбуки','noutbuki'),child('19010','Компьютеры / системные блоки','kompyutery')]),
 node('phones','Телефоны и планшеты','telefony-i-planshety',[child('17010','Мобильные телефоны','mobilnye-telefony'),child('phones_components','Комплектующие для телефонов','komplektuyushchie-dlya-telefonov'),child('phones_accessories','Аксессуары для телефонов','aksessuary-dlya-telefonov'),child('phones_telephony','Телефония и связь','telefoniya-i-svyaz'),child('phones_tablets','Планшеты','planshety'),child('phones_tablet_components','Комплектующие для планшетов','komplektuyushchie-dlya-planshetov'),child('phones_graphics','Графические планшеты','graficheskie-planshety'),child('phones_ebooks','Электронные книги','elektronnye-knigi'),child('phones_watches','Умные часы и фитнес-браслеты','umnye-chasy-i-fitnes-braslety'),child('phones_audio','Наушники','naushniki')]),
 node('electronics','Электроника','elektronika',[child('5020','Аудиотехника','audiotekhnika'),child('5060','ТВ и видеотехника','televizory'),child('5070','Фототехника и оптика','fototekhnika'),child('5040','Игры и приставки','igry-i-pristavki')]),
 node('women_clothes','Женский гардероб','zhenskij-garderob',[child('8080','Женская одежда','zhenskaya-odezhda'),child('8100','Женская обувь','zhenskaya-obuv'),child('8020','Аксессуары и часы','aksessuary-i-chasy'),child('8060','Одежда для беременных','odezhda-dlya-beremennyh')]),node('men_clothes','Мужской гардероб','muzhskoj-garderob',[child('8070','Мужская одежда','muzhskaya-odezhda'),child('8090','Мужская обувь','muzhskaya-obuv')]),
 node('beauty','Красота и здоровье','krasota-i-zdorove',[child('13040','Красота и здоровье','krasota-i-zdorove-uslugi'),child('7050','Медицинские товары','medicinskie-tovary')]),node('kids','Всё для детей и мам','vsyo-dlya-detej-i-mam',[child('12010','Одежда до 1 года','odezhda-do-goda'),child('12020','Детская обувь','detskaya-obuv'),child('12030','Кроватки, манежи, стульчики','krovatki'),child('12040','Ходунки, шезлонги, качели','hodunki'),child('12050','Коляски','kolyaski'),child('12060','Автокресла и бустеры','detskie-avtokresla'),child('12070','Кормление и уход','kormlenie-i-uhod'),child('12080','Сумки-кенгуру и слинги','sumki-kenguru'),child('12090','Игрушки и книги','igrushki-i-knigi'),child('12100','Детский транспорт','detskij-transport'),child('12110','Товары для мам','tovary-dlya-mam'),child('12120','Одежда для беременных','odezhda-dlya-beremennyh'),child('12130','Прочие товары для детей','prochie-detskie-tovary'),child('12140','Одежда для девочек','odezhda-dlya-devochek'),child('12150','Одежда для мальчиков','odezhda-dlya-malchikov'),child('12160','Текстиль для детей','tekstil')]),node('furniture','Мебель','mebel'),
 node('home','Все для дома','vse-dlya-doma',[]),node('repair','Ремонт и стройка','remont-i-strojka',[child('14010','Строительный инструмент','stroitelnye-instrumenty'),child('14020','Сантехника','santehnika'),child('14030','Стройматериалы','stroymaterialy'),child('14040','Отделочные материалы','otdelochnye-materialy'),child('14060','Прочее для ремонта и стройки','prochee-remont'),child('14070','Строительство и ремонт','stroitelstvo-remont')]),node('garden','Сад и огород','sad-i-ogorod',[child('10010','Садовая мебель и бассейны','sadovaya-mebel'),child('10020','Растения, рассада и семена','rasteniya'),child('10030','Садовая техника и инвентарь','sadovaya-tehnika'),child('10040','Теплицы','teplicy'),child('10050','Садовые аксессуары','sadovye-aksessuary'),child('10060','Удобрения и агрохимия','udobreniya'),child('10070','Всё для пчеловода','pchelovodstvo'),child('10080','Прочее для сада и огорода','prochee-sad'),child('10090','Бани, хозблоки, санузлы','bani-hozbloki')]),
 node('hobby','Хобби, спорт и туризм','hobby-sport-i-turizm',[child('4010','CD, DVD, пластинки','cd-dvd'),child('4020','Спорттовары','sporttovary')]),node('wedding','Свадьба и праздники','svadba-i-prazdniki',[child('9010','Подарки и праздничные товары','podarki'),child('9020','Свадебные платья','svadebnye-platya'),child('9030','Свадебные костюмы','svadebnye-kostyumy'),child('9040','Свадебная обувь','svadebnaya-obuv'),child('9050','Свадебные аксессуары','svadebnye-aksessuary'),child('9060','Услуги для торжеств','uslugi-torzhestv'),child('9070','Карнавальные костюмы','karnavalnye-kostyumy')]),node('animals','Животные','zhivotnye',[child('11010','Домашние питомцы','domashnie-pitomcy'),child('11020','Сельхоз животные','selhoz-zhivotnye'),child('11030','Товары для животных','tovary-dlya-zhivotnyh'),child('11040','Услуги для животных','uslugi-dlya-zhivotnyh'),child('11050','Вязка животных','vyazka'),child('11060','Питомцы в дар','pitomcy-v-dar')]),
 node('business','Готовый бизнес и оборудование','gotovyj-biznes-i-oborudovanie',[child('6050','Готовый бизнес','gotovyj-biznes'),child('6090','Станки и оборудование','stanki-oborudovanie')]),node('jobs','Работа','rabota',[child('6010','Вакансии','vakansii'),child('6020','Ищу работу','ischu-rabotu')]),node('other','Прочее','prochee',[child('7010','Все остальное','vse-ostalnoe'),child('7030','Бюро находок','byuro-nahodok'),child('7060','Канцелярские товары','kancelyariya'),child('7020','Продукты питания','produkty')])
];
const REGION_SLUGS:Record<string,string>={minsk:'minsk',brest:'brest',vitebsk:'vitebsk',gomel:'gomel',grodno:'grodno',mogilev:'mogilev',minskaya_oblast:'minskaya-oblast',brestskaya_oblast:'brestskaya-oblast',vitebskaya_oblast:'vitebskaya-oblast',gomelskaya_oblast:'gomelskaya-oblast',grodnenskaya_oblast:'grodnenskaya-oblast',mogilevskaya_oblast:'mogilevskaya-oblast'};
export function findCatalogNode(id:string):CatalogNode|null{for(const category of KUFAR_CATALOG){if(category.id===id)return category;const found=category.children?.find(item=>item.id===id);if(found)return found;}return null;}
export function findCatalogCategory(id:string):CatalogNode|null{const direct=KUFAR_CATALOG.find(category=>category.id===id);if(direct)return direct;return KUFAR_CATALOG.find(category=>category.children?.some(item=>item.id===id))||null;}
export function getCatalogLabel(id:string):string{return findCatalogNode(id)?.title||'Каталог';}
export function buildKufarSearchUrl(config:MonitorConfig):string{
 const selected=findCatalogNode(config.subcategoryId||config.categoryId); const category=findCatalogCategory(config.categoryId); const slug=selected?.slug||category?.slug||'';
 const city=config.city?encodeURIComponent(config.city):''; const region=config.region?REGION_SLUGS[config.region]||config.region:'';
 const prefix=city?'/l/r~'+city+'/':region?'/l/r~'+region+'/':'/l/'; const url=new URL(prefix+slug,'https://www.kufar.by');
 if(config.query?.trim())url.searchParams.set('query',config.query.trim());
 const min=config.minPrice!=null&&Number.isFinite(Number(config.minPrice))?Number(config.minPrice):undefined;
 const max=config.maxPrice!=null&&Number.isFinite(Number(config.maxPrice))?Number(config.maxPrice):undefined;
 if(min!=null||max!=null)url.searchParams.set('prc','r:'+(min??0)+','+(max??''));
 return url.toString();
}
