       ON CONFLICT (user_id,external_id) DO NOTHING
       RETURNING external_id`,
      [userId,linkId,rows],
    );
    return new Set(r.rows.map(row=>row.external_id));
  }

  async getRecentMarketAds(linkId:number,limit=250):Promise<Ad[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),20),1000);const r=await this.pool.query<Ad>('SELECT id,link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at,created_at FROM ads WHERE link_id=$1 AND price IS NOT NULL AND price <> \'\' ORDER BY COALESCE(published_at,created_at) DESC,id DESC LIMIT $2',[linkId,safeLimit]);return r.rows;}
  async getUserAdsCount(userId:number):Promise<{linkId:number;linkPlatform:string;count:number}[]>{const r=await this.pool.query('SELECT l.id as "linkId",l.platform as "linkPlatform",COUNT(a.id) as "count" FROM links l LEFT JOIN ads a ON a.link_id=l.id WHERE l.user_id=$1 GROUP BY l.id ORDER BY l.id',[userId]);return r.rows;}
  async clearAdsByUserId(userId:number):Promise<number>{const r=await this.pool.query<{id:number}>('SELECT id FROM links WHERE user_id=$1',[userId]);if(!r.rows.length)return 0;const d=await this.pool.query('DELETE FROM ads WHERE link_id=ANY($1::int[])',[r.rows.map(x=>x.id)]);await this.pool.query('DELETE FROM user_ad_seen WHERE user_id=$1',[userId]);return d.rowCount||0;}
  async getDashboardAds(userId:number,limit=50):Promise<DashboardAd[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),100);const r=await this.pool.query<DashboardAd>('SELECT a.*,l.platform AS link_platform,l.url AS link_url FROM ads a JOIN links l ON l.id=a.link_id LEFT JOIN user_ad_dismissed d ON d.user_id=l.user_id AND d.external_id=a.external_id WHERE l.user_id=$1 AND d.external_id IS NULL ORDER BY COALESCE(a.published_at,a.created_at) DESC,a.id DESC LIMIT $2',[userId,safeLimit]);return r.rows;}
  async dismissAdForUser(adId:number,userId:number):Promise<boolean>{const r=await this.pool.query<{external_id:string}>('SELECT a.external_id FROM ads a JOIN links l ON l.id=a.link_id WHERE a.id=$1 AND l.user_id=$2',[adId,userId]);const externalId=r.rows[0]?.external_id;if(!externalId)return false;await this.pool.query('INSERT INTO user_ad_dismissed (user_id,external_id) VALUES ($1,$2) ON CONFLICT (user_id,external_id) DO NOTHING',[userId,externalId]);return true;}
  async getDismissedExternalIds(userId:number,externalIds:string[]):Promise<Set<string>>{const ids=[...new Set(externalIds.filter(Boolean))];if(!ids.length)return new Set();const r=await this.pool.query<{external_id:string}>('SELECT external_id FROM user_ad_dismissed WHERE user_id=$1 AND external_id=ANY($2::text[])',[userId,ids]);return new Set(r.rows.map(row=>row.external_id));}
  async getDashboardPriceDrops(userId:number,limit=30):Promise<DashboardPriceDrop[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),50);const r=await this.pool.query<DashboardPriceDrop>('SELECT ph.id,ph.external_id,ph.old_price,ph.new_price,ph.price_change_percent,ph.created_at,a.title,a.image_url,a.ad_url,l.platform AS link_platform FROM price_history ph JOIN ads a ON a.id=ph.ad_id JOIN links l ON l.id=a.link_id WHERE ph.user_id=$1 ORDER BY ph.created_at DESC,ph.id DESC LIMIT $2',[userId,safeLimit]);return r.rows;}
  async getDashboardStats(userId:number):Promise<{activeLinks:number;totalLinks:number;adsToday:number;priceDropsToday:number}>{const r=await this.pool.query<{active_links:string;total_links:string;ads_today:string;drops_today:string}>('SELECT COUNT(*) FILTER (WHERE is_active) AS active_links,COUNT(*) AS total_links,(SELECT COUNT(*) FROM ads a JOIN links l ON a.link_id=l.id WHERE l.user_id=$1 AND a.created_at>=CURRENT_DATE) AS ads_today,(SELECT COUNT(*) FROM price_history ph WHERE ph.user_id=$1 AND ph.created_at>=CURRENT_DATE) AS drops_today FROM links WHERE user_id=$1',[userId]);const row=r.rows[0];return{activeLinks:Number(row?.active_links||0),totalLinks:Number(row?.total_links||0),adsToday:Number(row?.ads_today||0),priceDropsToday:Number(row?.drops_today||0)};}
  async createPriceDropRecord(userId:number,adId:number,externalId:string,oldPrice:string,newPrice:string,changePercent:number):Promise<boolean>{try{const r=await this.pool.query('INSERT INTO price_history (ad_id,user_id,external_id,old_price,new_price,price_change_percent,notified_at) VALUES ($1,$2,$3,$4,$5,$6,NULL) ON CONFLICT (user_id,external_id,old_price,new_price) DO NOTHING',[adId,userId,externalId,oldPrice,newPrice,changePercent]);return(r.rowCount||0)>0;}catch(error:unknown){const message=error instanceof Error?error.message:String(error);logger.warn('Price drop record insert failed',{error:message});return false;}}
  async updateAdMarketSignals(signals:Array<{id:number;status:'below_market'|'market'|'above_market'|null;percent:number|null;median:number|null;low:number|null;high:number|null;sellFast:number|null;sellNormal:number|null;sellMax:number|null;sampleSize:number|null;confidence:'low'|'medium'|'high'|null;quality:number|null}>):Promise<void>{
    if(!signals.length)return;
    await this.pool.query(
      `UPDATE ads a
       SET market_status=x.status,
           market_percent=x.percent,
           market_median=x.median,
           market_low=x.low,
           market_high=x.high,
           sell_fast=x.sell_fast,
           sell_normal=x.sell_normal,
           sell_max=x.sell_max,
           market_sample_size=x.sample_size,
           market_confidence=x.confidence,
           market_quality=x.quality
       FROM jsonb_to_recordset($1::jsonb) AS x(id int,status text,percent numeric,median numeric,low numeric,high numeric,sell_fast numeric,sell_normal numeric,sell_max numeric,sample_size int,confidence text,quality numeric)
       WHERE a.id=x.id`,
      [JSON.stringify(signals.map(s=>({id:s.id,status:s.status,percent:s.percent,median:s.median,low:s.low,high:s.high,sell_fast:s.sellFast,sell_normal:s.sellNormal,sell_max:s.sellMax,sample_size:s.sampleSize,confidence:s.confidence,quality:s.quality})))],
    );
  }

  async updateAdPrice(adId:number,newPrice:string):Promise<void>{await this.pool.query('UPDATE ads SET price=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2',[newPrice,adId]);}
  async bulkUpdateAdPrices(updates:Array<{id:number;price:string}>):Promise<void>{if(!updates.length)return;const unique=new Map<number,string>();for(const item of updates)if(Number.isSafeInteger(item.id)&&item.id>0&&item.price)unique.set(item.id,item.price);if(!unique.size)return;await this.pool.query(`UPDATE ads a SET price=x.price,updated_at=CURRENT_TIMESTAMP FROM jsonb_to_recordset($1::jsonb) AS x(id int,price text) WHERE a.id=x.id`,[JSON.stringify([...unique].map(([id,price])=>({id,price})))]);}
  async enqueueNotifications(jobs:NotificationEnqueueJob[]):Promise<number>{if(!jobs.length)return 0;let inserted=0;const chunkSize=400;for(let start=0;start<jobs.length;start+=chunkSize){const chunk=jobs.slice(start,start+chunkSize);const values:unknown[]=[];const placeholders=chunk.map((job,i)=>{const b=i*4;values.push(job.kind,job.chatId,job.dedupeKey,JSON.stringify(job.payload));return`($${b+1},$${b+2},$${b+3},$${b+4}::jsonb)`;}).join(',');const result=await this.pool.query(`INSERT INTO notification_outbox (kind,chat_id,dedupe_key,payload) VALUES ${placeholders} ON CONFLICT (dedupe_key) DO NOTHING`,values);inserted+=result.rowCount||0;}return inserted;}
  async claimNotificationJobs(limit=25,leaseSeconds=60):Promise<NotificationJob[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),100);const safeLease=Math.min(Math.max(Math.floor(leaseSeconds),5),3600);const r=await this.pool.query<NotificationJob>(`WITH candidates AS (SELECT id FROM notification_outbox WHERE sent_at IS NULL AND dead_lettered_at IS NULL AND available_at<=CURRENT_TIMESTAMP AND (locked_until IS NULL OR locked_until<CURRENT_TIMESTAMP) ORDER BY id LIMIT $1 FOR UPDATE SKIP LOCKED) UPDATE notification_outbox n SET locked_until=CURRENT_TIMESTAMP+($2::int * INTERVAL '1 second') FROM candidates c WHERE n.id=c.id RETURNING n.*`,[safeLimit,safeLease]);return r.rows;}
  async markNotificationSent(id:number):Promise<void>{await this.pool.query('UPDATE notification_outbox SET sent_at=CURRENT_TIMESTAMP,locked_until=NULL,last_error=NULL WHERE id=$1',[id]);}
  async rescheduleNotification(id:number,errorMessage:string,delaySeconds:number):Promise<void>{const delay=Math.min(Math.max(Math.floor(delaySeconds),1),3600);await this.pool.query("UPDATE notification_outbox SET attempts=attempts+1,available_at=CURRENT_TIMESTAMP+($2::int * INTERVAL '1 second'),locked_until=NULL,last_error=$3 WHERE id=$1 AND sent_at IS NULL",[id,delay,errorMessage.slice(0,2000)]);}