import { Pool, PoolClient } from 'pg';
import { readFileSync } from 'fs';
import { join } from 'path';
import { User, Link, Ad, Platform } from '../types';
import { logger } from '../utils/logger';
import { MonitorConfig, buildKufarSearchUrl } from '../catalog/KufarCatalog';

export interface DashboardAd extends Ad { link_platform: Platform; link_url: string; }
export interface DashboardPriceDrop { id:number; external_id:string; old_price:string|null; new_price:string|null; price_change_percent:number|null; created_at:Date; title:string; image_url:string|null; ad_url:string; link_platform:Platform; }
export type NotificationKind = 'new_ad' | 'price_drop';
export interface NotificationEnqueueJob { kind:NotificationKind; chatId:number; dedupeKey:string; payload:Record<string, unknown>; }
export interface NotificationJob { id:number; kind:NotificationKind; chat_id:number; dedupe_key:string; payload:Record<string, unknown>; attempts:number; available_at:Date; locked_until:Date|null; sent_at:Date|null; last_error:string|null; created_at:Date; }

export class DatabaseService {
  private pool: Pool;
  constructor(connectionString:string){this.pool=new Pool({connectionString,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:5000,statement_timeout:12000,query_timeout:12000,keepAlive:true,keepAliveInitialDelayMillis:10000});this.pool.on('error',(err:Error)=>logger.error('Unexpected database error',{error:err.message}));}
  async initialize():Promise<void>{try{await this.pool.query(readFileSync(join(__dirname,'schema.sql'),'utf-8'));logger.info('Database schema initialized');}catch(error){logger.error('Failed to initialize database',{error});throw error;}}
  async healthCheck():Promise<{ok:boolean;latencyMs:number}>{const started=Date.now();await this.pool.query('SELECT 1');return{ok:true,latencyMs:Date.now()-started};}
  async close():Promise<void>{await this.pool.end();}
  async createUser(telegramId:number,username:string|null):Promise<User>{const r=await this.pool.query<User>('INSERT INTO users (telegram_id, username) VALUES ($1,$2) ON CONFLICT (telegram_id) DO UPDATE SET username=COALESCE(EXCLUDED.username, users.username) RETURNING *',[telegramId,username]);return r.rows[0];}
  async getUser(telegramId:number):Promise<User|null>{const r=await this.pool.query<User>('SELECT * FROM users WHERE telegram_id=$1',[telegramId]);return r.rows[0]||null;}
  async getUserById(userId:number):Promise<User|null>{const r=await this.pool.query<User>('SELECT * FROM users WHERE id=$1',[userId]);return r.rows[0]||null;}
  async getUsersByIds(userIds:number[]):Promise<User[]>{const ids=[...new Set(userIds.filter(id=>Number.isSafeInteger(id)&&id>0))];if(!ids.length)return[];const r=await this.pool.query<User>('SELECT * FROM users WHERE id=ANY($1::int[])',[ids]);return r.rows;}
  private monitorSourceKey(config:MonitorConfig):string{const min=config.minPrice==null?'':String(config.minPrice);const max=config.maxPrice==null?'':String(config.maxPrice);return [config.source,config.categoryId,config.subcategoryId||'',config.region||'',config.city||'',config.query||'',min,max,config.condition||'',config.seller||'',config.mode||'normal'].join(':');}
  async createLink(userId:number,url:string,platform:Platform,config?:MonitorConfig):Promise<Link>{const sourceKey=config ? this.monitorSourceKey(config) : null;const configJson=config ? JSON.stringify(config) : null;const r=await this.pool.query<Link>('INSERT INTO links (user_id,url,platform,config,source_key,next_check_at,priority) VALUES ($1,$2,$3,$4::jsonb,$5,CURRENT_TIMESTAMP,CASE WHEN ($4::jsonb->>\'mode\')=\'sniper\' THEN 100 ELSE 0 END) ON CONFLICT (user_id,url) DO UPDATE SET is_active=true, platform=EXCLUDED.platform, config=COALESCE(EXCLUDED.config,links.config), source_key=COALESCE(EXCLUDED.source_key,links.source_key), error_count=0, next_check_at=CURRENT_TIMESTAMP, priority=EXCLUDED.priority RETURNING *',[userId,url,platform,configJson,sourceKey]);return r.rows[0];}
  async createMonitorFromConfig(userId:number,config:MonitorConfig,initialAds:Ad[]):Promise<Link>{const url=buildKufarSearchUrl(config);return this.createLinkWithConfigAndInitialAds(userId,url,'kufar',config,initialAds);}
  async createLinkWithConfigAndInitialAds(userId:number,url:string,platform:Platform,config:MonitorConfig,initialAds:Ad[]):Promise<Link>{const client=await this.pool.connect();try{await client.query('BEGIN');const sourceKey=this.monitorSourceKey(config);const linkResult=await client.query<Link>('INSERT INTO links (user_id,url,platform,config,source_key,next_check_at,priority) VALUES ($1,$2,$3,$4::jsonb,$5,CURRENT_TIMESTAMP,CASE WHEN ($4::jsonb->>\'mode\')=\'sniper\' THEN 100 ELSE 0 END) ON CONFLICT (user_id,url) DO UPDATE SET is_active=true,platform=EXCLUDED.platform,config=EXCLUDED.config,source_key=EXCLUDED.source_key,error_count=0,next_check_at=CURRENT_TIMESTAMP,priority=EXCLUDED.priority RETURNING *',[userId,url,platform,JSON.stringify(config),sourceKey]);const link=linkResult.rows[0];const unique=new Map<string,Ad>();for(const ad of initialAds)if(ad?.external_id&&!unique.has(ad.external_id))unique.set(ad.external_id,ad);const rows=[...unique.values()];for(let start=0;start<rows.length;start+=400){const chunk=rows.slice(start,start+400);const values:any[]=[];const placeholders=chunk.map((ad,i)=>{const b=i*11;values.push(link.id,ad.external_id,ad.title,ad.description||null,ad.price||null,ad.image_url||null,ad.ad_url,ad.location||null,ad.address||null,ad.published_at||null,ad.updated_at||null);return`(${b+1},${b+2},${b+3},${b+4},${b+5},${b+6},${b+7},${b+8},${b+9},${b+10},${b+11})`;}).join(',');if(values.length)await client.query(`INSERT INTO ads (link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at) VALUES ${placeholders} ON CONFLICT (external_id,link_id) DO NOTHING`,values);}if(rows.length)await client.query(`INSERT INTO user_ad_seen (user_id,external_id,first_link_id) SELECT $1,x,$2 FROM unnest($3::text[]) AS x ON CONFLICT (user_id,external_id) DO NOTHING`,[userId,link.id,rows.map(ad=>ad.external_id)]);await client.query('UPDATE links SET last_parsed_at=CURRENT_TIMESTAMP,next_check_at=CURRENT_TIMESTAMP WHERE id=$1',[link.id]);await client.query('COMMIT');return (await this.getLink(link.id))||link;}catch(error){try{await client.query('ROLLBACK');}catch{}throw error;}finally{client.release();}}
  async createLinkWithInitialAds(userId:number,url:string,platform:Platform,initialAds:Ad[]):Promise<Link>{const client:PoolClient=await this.pool.connect();try{await client.query('BEGIN');const linkResult=await client.query<Link>('INSERT INTO links (user_id,url,platform) VALUES ($1,$2,$3) ON CONFLICT (user_id,url) DO UPDATE SET is_active=true, platform=EXCLUDED.platform, error_count=0 RETURNING *',[userId,url,platform]);const link=linkResult.rows[0];const unique=new Map<string,Ad>();for(const ad of initialAds)if(ad?.external_id&&!unique.has(ad.external_id))unique.set(ad.external_id,ad);const rows=[...unique.values()];const chunkSize=400;for(let start=0;start<rows.length;start+=chunkSize){const chunk=rows.slice(start,start+chunkSize);const values:unknown[]=[];const placeholders=chunk.map((ad,i)=>{const b=i*11;values.push(link.id,ad.external_id,ad.title,ad.description||null,ad.price||null,ad.image_url||null,ad.ad_url,ad.location||null,ad.address||null,ad.published_at||null,ad.updated_at||null);return`($${b+1},$${b+2},$${b+3},$${b+4},$${b+5},$${b+6},$${b+7},$${b+8},$${b+9},$${b+10},$${b+11})`;}).join(',');await client.query(`INSERT INTO ads (link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at) VALUES ${placeholders} ON CONFLICT (external_id,link_id) DO NOTHING`,values);}if(rows.length){await client.query(`INSERT INTO user_ad_seen (user_id,external_id,first_link_id) SELECT $1,x,$2 FROM unnest($3::text[]) AS x ON CONFLICT (user_id,external_id) DO NOTHING`,[userId,link.id,rows.map(ad=>ad.external_id)]);}await client.query('UPDATE links SET last_parsed_at=CURRENT_TIMESTAMP WHERE id=$1',[link.id]);await client.query('COMMIT');logger.info('Link atomically bootstrapped with initial ads',{linkId:link.id,userId,platform,url,initialAds:rows.length});const refreshed=await this.getLink(link.id);return refreshed||link;}catch(error){try{await client.query('ROLLBACK');}catch{}throw error;}finally{client.release();}}
  async getUserLinks(userId:number):Promise<Link[]>{const r=await this.pool.query<Link>('SELECT * FROM links WHERE user_id=$1 ORDER BY created_at DESC',[userId]);return r.rows;}
  async getUserLinksCount(userId:number):Promise<number>{const r=await this.pool.query<{count:string}>('SELECT COUNT(*) as count FROM links WHERE user_id=$1 AND is_active=true',[userId]);return parseInt(r.rows[0].count,10);}
  async getLink(linkId:number):Promise<Link|null>{const r=await this.pool.query<Link>('SELECT * FROM links WHERE id=$1',[linkId]);return r.rows[0]||null;}
  async getLinkForUser(linkId:number,userId:number):Promise<Link|null>{const r=await this.pool.query<Link>('SELECT * FROM links WHERE id=$1 AND user_id=$2',[linkId,userId]);return r.rows[0]||null;}
  async deleteLink(linkId:number,userId?:number):Promise<boolean>{const query=userId==null?'DELETE FROM links WHERE id=$1':'DELETE FROM links WHERE id=$1 AND user_id=$2';const params=userId==null?[linkId]:[linkId,userId];const r=await this.pool.query(query,params);return(r.rowCount||0)>0;}
  async setLinkActive(linkId:number,userId:number,isActive:boolean):Promise<boolean>{const r=await this.pool.query('UPDATE links SET is_active=$1,error_count=CASE WHEN $1 THEN 0 ELSE error_count END WHERE id=$2 AND user_id=$3 AND ($1=false OR (SELECT COUNT(*) FROM links AS active_links WHERE active_links.user_id=$3 AND active_links.is_active=true AND active_links.id<>$2)<50)',[isActive,linkId,userId]);return(r.rowCount||0)>0;}
  async getActiveLinks():Promise<Link[]>{const r=await this.pool.query<Link>('SELECT * FROM links WHERE is_active=true AND (next_check_at IS NULL OR next_check_at<=CURRENT_TIMESTAMP) ORDER BY COALESCE(next_check_at,CURRENT_TIMESTAMP),priority DESC,id',[]);return r.rows;}
  async scheduleNextCheck(linkId:number,delayMs:number):Promise<void>{await this.scheduleNextChecks([{linkId,delayMs}]);}
  async scheduleNextChecks(items:Array<{linkId:number;delayMs:number}>):Promise<void>{if(!items.length)return;const unique=new Map<number,number>();for(const item of items){if(!Number.isSafeInteger(item.linkId)||item.linkId<=0)continue;unique.set(item.linkId,Math.min(Math.max(Math.floor(item.delayMs),250),300000));}if(!unique.size)return;const values=[...unique.entries()];const cases=values.map((entry,index)=>`WHEN id=${index*2+1} THEN CURRENT_TIMESTAMP+(${index*2+2}::int * INTERVAL '1 millisecond')`).join(' ');const params=values.flatMap(([id,delay])=>[id,delay]);const ids=values.map((entry,index)=>`${index*2+1}`).join(',');await this.pool.query(`UPDATE links SET next_check_at=CASE ${cases} END WHERE is_active=true AND id IN (${ids})`,params);}
  async incrementErrorCount(linkId:number):Promise<void>{await this.pool.query('UPDATE links SET error_count=error_count+1 WHERE id=$1',[linkId]);}
  async markLinkInactive(linkId:number):Promise<void>{await this.pool.query('UPDATE links SET is_active=false WHERE id=$1',[linkId]);}
  async updateLastParsed(linkId:number):Promise<void>{await this.pool.query('UPDATE links SET last_parsed_at=CURRENT_TIMESTAMP WHERE id=$1',[linkId]);}
  async resetErrorCount(linkId:number):Promise<void>{await this.pool.query('UPDATE links SET error_count=0 WHERE id=$1',[linkId]);}
  async createAd(linkId:number,adData:Ad):Promise<Ad|null>{const r=await this.pool.query<Ad>('INSERT INTO ads (link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (external_id,link_id) DO NOTHING RETURNING *',[linkId,adData.external_id,adData.title,adData.description||null,adData.price||null,adData.image_url||null,adData.ad_url,adData.location||null,adData.address||null,adData.published_at||null,adData.updated_at||null]);return r.rows[0]||null;}
  async bulkCreateAds(linkId:number,ads:Ad[]):Promise<number>{const unique=new Map<string,Ad>();for(const ad of ads)if(ad?.external_id&&!unique.has(ad.external_id))unique.set(ad.external_id,ad);const rows=[...unique.values()];if(!rows.length)return 0;let inserted=0;const chunkSize=400;for(let start=0;start<rows.length;start+=chunkSize){const chunk=rows.slice(start,start+chunkSize);const values:unknown[]=[];const placeholders=chunk.map((ad,i)=>{const b=i*11;values.push(linkId,ad.external_id,ad.title,ad.description||null,ad.price||null,ad.image_url||null,ad.ad_url,ad.location||null,ad.address||null,ad.published_at||null,ad.updated_at||null);return`($${b+1},$${b+2},$${b+3},$${b+4},$${b+5},$${b+6},$${b+7},$${b+8},$${b+9},$${b+10},$${b+11})`;}).join(',');const result=await this.pool.query(`INSERT INTO ads (link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at) VALUES ${placeholders} ON CONFLICT (external_id,link_id) DO NOTHING`,values);inserted+=result.rowCount||0;}return inserted;}
  async bulkCreateAdsReturning(linkId:number,ads:Ad[]):Promise<Ad[]>{const unique=new Map<string,Ad>();for(const ad of ads)if(ad?.external_id&&!unique.has(ad.external_id))unique.set(ad.external_id,ad);const rows=[...unique.values()];if(!rows.length)return[];const inserted:Ad[]=[];const chunkSize=400;for(let start=0;start<rows.length;start+=chunkSize){const chunk=rows.slice(start,start+chunkSize);const values:unknown[]=[];const placeholders=chunk.map((ad,i)=>{const b=i*11;values.push(linkId,ad.external_id,ad.title,ad.description||null,ad.price||null,ad.image_url||null,ad.ad_url,ad.location||null,ad.address||null,ad.published_at||null,ad.updated_at||null);return`($${b+1},$${b+2},$${b+3},$${b+4},$${b+5},$${b+6},$${b+7},$${b+8},$${b+9},$${b+10},$${b+11})`;}).join(',');const result=await this.pool.query<Ad>(`INSERT INTO ads (link_id,external_id,title,description,price,image_url,ad_url,location,address,published_at,updated_at) VALUES ${placeholders} ON CONFLICT (external_id,link_id) DO NOTHING RETURNING *`,values);inserted.push(...result.rows);}return inserted;}
  async getAdByIdForUser(adId:number,userId:number):Promise<Ad|null>{const r=await this.pool.query<Ad>('SELECT a.* FROM ads a JOIN links l ON l.id=a.link_id WHERE a.id=$1 AND l.user_id=$2',[adId,userId]);return r.rows[0]||null;}
  async getAdByExternalId(externalId:string):Promise<Ad|null>{const r=await this.pool.query<Ad>('SELECT * FROM ads WHERE external_id=$1 ORDER BY id LIMIT 1',[externalId]);return r.rows[0]||null;}
  async isNewAd(externalId:string):Promise<boolean>{return(await this.getAdByExternalId(externalId))===null;}
  async isNewAdForLink(linkId:number,externalId:string):Promise<boolean>{const r=await this.pool.query('SELECT id FROM ads WHERE link_id=$1 AND external_id=$2',[linkId,externalId]);return r.rows.length===0;}
  async isNewAdForUser(userId:number,externalId:string):Promise<boolean>{const r=await this.pool.query('SELECT a.id FROM ads a JOIN links l ON a.link_id=l.id WHERE l.user_id=$1 AND a.external_id=$2',[userId,externalId]);return r.rows.length===0;}
  async getExistingAdExternalIdsForLink(linkId:number,externalIds:string[]):Promise<Set<string>>{if(!externalIds.length)return new Set();const r=await this.pool.query<{external_id:string}>('SELECT external_id FROM ads WHERE link_id=$1 AND external_id=ANY($2::text[])',[linkId,externalIds]);return new Set(r.rows.map(x=>x.external_id));}
  async markAdsSeenForUser(userId:number,linkId:number,ads:Ad[]):Promise<void>{
    const rows=ads.filter(ad=>ad?.external_id).map(ad=>ad.external_id);
    if(!rows.length)return;
    await this.pool.query(
      `INSERT INTO user_ad_seen (user_id,external_id,first_link_id)
       SELECT $1, x, $2 FROM unnest($3::text[]) AS x
       ON CONFLICT (user_id,external_id) DO NOTHING`,
      [userId,linkId,[...new Set(rows)]],
    );
  }

  async claimNewAdsForUser(userId:number,linkId:number,ads:Ad[]):Promise<Set<string>>{
    const rows=[...new Set(ads.filter(ad=>ad?.external_id).map(ad=>ad.external_id))];
    if(!rows.length)return new Set();
    const r=await this.pool.query<{external_id:string}>(
      `INSERT INTO user_ad_seen (user_id,external_id,first_link_id)
       SELECT $1, x, $2 FROM unnest($3::text[]) AS x
       ON CONFLICT (user_id,external_id) DO NOTHING
       RETURNING external_id`,
      [userId,linkId,rows],
    );
    return new Set(r.rows.map(row=>row.external_id));
  }

  async getExistingAdExternalIdsForUser(userId:number,externalIds:string[]):Promise<Set<string>>{if(!externalIds.length)return new Set();const r=await this.pool.query<{external_id:string}>('SELECT DISTINCT a.external_id FROM ads a JOIN links l ON a.link_id=l.id WHERE l.user_id=$1 AND a.external_id=ANY($2::text[])',[userId,externalIds]);return new Set(r.rows.map(x=>x.external_id));}
  async getLastPricesForAds(linkId:number,externalIds:string[]):Promise<Map<string,{price:string;adId:number}>>{if(!externalIds.length)return new Map();const r=await this.pool.query<{external_id:string;price:string;ad_id:number}>('SELECT DISTINCT ON (external_id) external_id,price,id as ad_id FROM ads WHERE link_id=$1 AND external_id=ANY($2::text[]) ORDER BY external_id,updated_at DESC NULLS LAST,id DESC',[linkId,externalIds]);return new Map(r.rows.filter(x=>x.price!=null).map(x=>[x.external_id,{price:x.price,adId:x.ad_id}]));}
  async getRecentMarketPrices(linkId:number,limit=250):Promise<string[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),20),1000);const r=await this.pool.query<{price:string}>('SELECT price FROM ads WHERE link_id=$1 AND price IS NOT NULL AND price <> \'\' ORDER BY COALESCE(published_at,created_at) DESC,id DESC LIMIT $2',[linkId,safeLimit]);return r.rows.map(x=>x.price).filter(Boolean);}
  async getUserAdsCount(userId:number):Promise<{linkId:number;linkPlatform:string;count:number}[]>{const r=await this.pool.query('SELECT l.id as "linkId",l.platform as "linkPlatform",COUNT(a.id) as "count" FROM links l LEFT JOIN ads a ON a.link_id=l.id WHERE l.user_id=$1 GROUP BY l.id ORDER BY l.id',[userId]);return r.rows;}
  async clearAdsByUserId(userId:number):Promise<number>{const r=await this.pool.query<{id:number}>('SELECT id FROM links WHERE user_id=$1',[userId]);if(!r.rows.length)return 0;const d=await this.pool.query('DELETE FROM ads WHERE link_id=ANY($1::int[])',[r.rows.map(x=>x.id)]);await this.pool.query('DELETE FROM user_ad_seen WHERE user_id=$1',[userId]);return d.rowCount||0;}
  async getDashboardAds(userId:number,limit=50):Promise<DashboardAd[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),100);const r=await this.pool.query<DashboardAd>('SELECT a.*,l.platform AS link_platform,l.url AS link_url FROM ads a JOIN links l ON l.id=a.link_id WHERE l.user_id=$1 ORDER BY COALESCE(a.published_at,a.created_at) DESC,a.id DESC LIMIT $2',[userId,safeLimit]);return r.rows;}
  async getDashboardPriceDrops(userId:number,limit=30):Promise<DashboardPriceDrop[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),50);const r=await this.pool.query<DashboardPriceDrop>('SELECT ph.id,ph.external_id,ph.old_price,ph.new_price,ph.price_change_percent,ph.created_at,a.title,a.image_url,a.ad_url,l.platform AS link_platform FROM price_history ph JOIN ads a ON a.id=ph.ad_id JOIN links l ON l.id=a.link_id WHERE ph.user_id=$1 ORDER BY ph.created_at DESC,ph.id DESC LIMIT $2',[userId,safeLimit]);return r.rows;}
  async getDashboardStats(userId:number):Promise<{activeLinks:number;totalLinks:number;adsToday:number;priceDropsToday:number}>{const r=await this.pool.query<{active_links:string;total_links:string;ads_today:string;drops_today:string}>('SELECT COUNT(*) FILTER (WHERE is_active) AS active_links,COUNT(*) AS total_links,(SELECT COUNT(*) FROM ads a JOIN links l ON a.link_id=l.id WHERE l.user_id=$1 AND a.created_at>=CURRENT_DATE) AS ads_today,(SELECT COUNT(*) FROM price_history ph WHERE ph.user_id=$1 AND ph.created_at>=CURRENT_DATE) AS drops_today FROM links WHERE user_id=$1',[userId]);const row=r.rows[0];return{activeLinks:Number(row?.active_links||0),totalLinks:Number(row?.total_links||0),adsToday:Number(row?.ads_today||0),priceDropsToday:Number(row?.drops_today||0)};}
  async getLastPriceForAd(linkId:number,externalId:string):Promise<{price:string;adId:number}|null>{const r=await this.pool.query('SELECT a.price,a.id as ad_id FROM ads a WHERE a.link_id=$1 AND a.external_id=$2 ORDER BY a.updated_at DESC NULLS LAST,a.id DESC LIMIT 1',[linkId,externalId]);return r.rows[0]||null;}
  parsePriceToNumber(priceStr:string|null|undefined):number|null{if(!priceStr)return null;const normalized=priceStr.replace(/\s+/g,'').replace(',','.');const m=normalized.match(/(\d+(?:\.\d+)?)/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)?n:null;}
  async createPriceDropRecord(userId:number,adId:number,externalId:string,oldPrice:string,newPrice:string,changePercent:number):Promise<boolean>{try{const r=await this.pool.query('INSERT INTO price_history (ad_id,user_id,external_id,old_price,new_price,price_change_percent,notified_at) VALUES ($1,$2,$3,$4,$5,$6,NULL) ON CONFLICT (user_id,external_id,old_price,new_price) DO NOTHING',[adId,userId,externalId,oldPrice,newPrice,changePercent]);return(r.rowCount||0)>0;}catch(error:unknown){const message=error instanceof Error?error.message:String(error);logger.warn('Price drop record insert failed',{error:message});return false;}}
  async updateAdMarketSignals(signals:Array<{id:number;status:'below_market'|'market'|'above_market'|null;percent:number|null;median:number|null}>):Promise<void>{
    if(!signals.length)return;
    await this.pool.query(
      `UPDATE ads a
       SET market_status=x.status,
           market_percent=x.percent,
           market_median=x.median
       FROM jsonb_to_recordset($1::jsonb) AS x(id int,status text,percent numeric,median numeric)
       WHERE a.id=x.id`,
      [JSON.stringify(signals.map(s=>({id:s.id,status:s.status,percent:s.percent,median:s.median})))],
    );
  }

  async updateAdPrice(adId:number,newPrice:string):Promise<void>{await this.pool.query('UPDATE ads SET price=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2',[newPrice,adId]);}
  async enqueueNotification(kind:NotificationKind,chatId:number,dedupeKey:string,payload:Record<string,unknown>):Promise<boolean>{const r=await this.pool.query('INSERT INTO notification_outbox (kind,chat_id,dedupe_key,payload) VALUES ($1,$2,$3,$4::jsonb) ON CONFLICT (dedupe_key) DO NOTHING RETURNING id',[kind,chatId,dedupeKey,JSON.stringify(payload)]);return(r.rowCount||0)>0;}
  async enqueueNotifications(jobs:NotificationEnqueueJob[]):Promise<number>{if(!jobs.length)return 0;let inserted=0;const chunkSize=400;for(let start=0;start<jobs.length;start+=chunkSize){const chunk=jobs.slice(start,start+chunkSize);const values:unknown[]=[];const placeholders=chunk.map((job,i)=>{const b=i*4;values.push(job.kind,job.chatId,job.dedupeKey,JSON.stringify(job.payload));return`($${b+1},$${b+2},$${b+3},$${b+4}::jsonb)`;}).join(',');const result=await this.pool.query(`INSERT INTO notification_outbox (kind,chat_id,dedupe_key,payload) VALUES ${placeholders} ON CONFLICT (dedupe_key) DO NOTHING`,values);inserted+=result.rowCount||0;}return inserted;}
  async claimNotificationJobs(limit=25,leaseSeconds=60):Promise<NotificationJob[]>{const safeLimit=Math.min(Math.max(Math.floor(limit),1),100);const safeLease=Math.min(Math.max(Math.floor(leaseSeconds),5),3600);const r=await this.pool.query<NotificationJob>(`WITH candidates AS (SELECT id FROM notification_outbox WHERE sent_at IS NULL AND available_at<=CURRENT_TIMESTAMP AND (locked_until IS NULL OR locked_until<CURRENT_TIMESTAMP) ORDER BY id LIMIT $1 FOR UPDATE SKIP LOCKED) UPDATE notification_outbox n SET locked_until=CURRENT_TIMESTAMP+($2::int * INTERVAL '1 second') FROM candidates c WHERE n.id=c.id RETURNING n.*`,[safeLimit,safeLease]);return r.rows;}
  async markNotificationSent(id:number):Promise<void>{await this.pool.query('UPDATE notification_outbox SET sent_at=CURRENT_TIMESTAMP,locked_until=NULL,last_error=NULL WHERE id=$1',[id]);}
  async rescheduleNotification(id:number,errorMessage:string,delaySeconds:number):Promise<void>{const delay=Math.min(Math.max(Math.floor(delaySeconds),1),3600);await this.pool.query("UPDATE notification_outbox SET attempts=attempts+1,available_at=CURRENT_TIMESTAMP+($2::int * INTERVAL '1 second'),locked_until=NULL,last_error=$3 WHERE id=$1 AND sent_at IS NULL",[id,delay,errorMessage.slice(0,2000)]);}
  async discardNotification(id:number,errorMessage:string):Promise<void>{await this.pool.query('DELETE FROM notification_outbox WHERE id=$1 AND sent_at IS NULL',[id]);logger.warn('Notification discarded after retry limit',{jobId:id,error:errorMessage.slice(0,500)});}
  async releaseNotificationLease(id:number):Promise<void>{await this.pool.query('UPDATE notification_outbox SET locked_until=NULL WHERE id=$1 AND sent_at IS NULL',[id]);}
  async getPendingNotificationCount():Promise<number>{const r=await this.pool.query<{count:string}>('SELECT COUNT(*) AS count FROM notification_outbox WHERE sent_at IS NULL',[]);return Number(r.rows[0]?.count||0);}
  async getPendingNotificationStats():Promise<{count:number;oldestAgeMs:number}>{const r=await this.pool.query<{count:string;oldest_at:Date|null}>('SELECT COUNT(*) AS count, MIN(created_at) AS oldest_at FROM notification_outbox WHERE sent_at IS NULL',[]);const row=r.rows[0];const oldest=row?.oldest_at instanceof Date?row.oldest_at:null;return {count:Number(row?.count||0),oldestAgeMs:oldest?Math.max(0,Date.now()-oldest.getTime()):0};}
  async getActiveLinkFreshnessStats():Promise<{activeLinks:number;oldestAgeMs:number;avgAgeMs:number}>{const r=await this.pool.query<{active_links:string;oldest_at:Date|null;avg_age_ms:string|null}>(`SELECT COUNT(*) FILTER (WHERE is_active) AS active_links,MIN(last_parsed_at) FILTER (WHERE is_active) AS oldest_at,COALESCE(AVG(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-COALESCE(last_parsed_at,created_at)))*1000) FILTER (WHERE is_active),0) AS avg_age_ms FROM links`,[]);const row=r.rows[0];const oldest=row?.oldest_at instanceof Date?row.oldest_at:null;return{activeLinks:Number(row?.active_links||0),oldestAgeMs:oldest?Math.max(0,Date.now()-oldest.getTime()):0,avgAgeMs:Number(row?.avg_age_ms||0)};}
  async purgeNotificationOutbox(retentionDays=14):Promise<number>{const safeDays=Math.min(Math.max(Math.floor(retentionDays),1),365);const r=await this.pool.query('DELETE FROM notification_outbox WHERE sent_at IS NOT NULL AND sent_at < CURRENT_TIMESTAMP - ($1::int * INTERVAL \'1 day\')',[safeDays]);return r.rowCount||0;}
}
